[[mgr.prepend_keymap]]
on = [ "g", "c" ]
run = "cd ~/.dots/home/.config"
desc = "Cd to .config"

[[mgr.prepend_keymap]]
on = [ "g", "h" ]
run = "cd ~/.dots"
desc = "Cd to dotfiles"

[[mgr.prepend_keymap]]
on = [ "g", "o" ]
run = "cd ~/.config"
desc = "Cd to .config"

[[mgr.prepend_keymap]]
on = [ "g", "p" ]
run = "cd ~/Projects/"
desc = "Cd to Projects"

[[mgr.prepend_keymap]]
on = [ "g", "m" ]
run = "cd ~/.config/mpv/playlists/"
desc = "Cd to Musics"
