[managers.system]
items = [
	# browser
	"qutebrowser",

    # editor
    "emacs",
	"ripgrep",

	"neovim",

	# runner
	"anyrun-git",

	# file browser
	"yazi",
	"fzf",

    # mpv
    "mpv",
    "svp-bin",
    "yt-dlp",
	
	# vial
	"vial-appimage",
]