[managers.system]
items = [
	# browser
	"qutebrowser",

    # editor
    "emacs",
	"neovim",

	# runner
	"anyrun-git",

	# file browser
	"yazi",
	"fzf",

    # mpv
    "mpv",
    "svp-bin",
    "yt-dlp",
]
