[managers.system]
items = [
"tealdeer",
"lazygit",
"starship",
"ttf-firacode-nerd",
"ttf-koruri",
"nodejs",
"unzip",
"npm",
"go",


"ags-hyprpanel-git",
#
"swww",
"brightnessctl",
"pacman-contrib",
"power-profiles-daemon",
"grimblast",
"gpu-screen-recorder",
"hyprpicker",
"hypridle",
"btop",
"matugen",
"libgtop",
"bluez",
"bluez-utils",
"networkmanager",
"dart-sass",
"wl-clipboard",
"upower",
"gvfs",
"xdg-desktop-portal-hyprland",


"hyprland",
#
"hyprpolkitagent",
"qt5-wayland",
"qt6-wayland",
"hyprcursor",
"kitty",


"wev",
]
