[managers.system]
items = [
    # arduino
    "arduino-cli",
    "7zip",

    # java
    "jdk-openjdk",
    "gradle",

	# hyprland
	"pixman",

	# utils
	"hyprutils-git",
	"hyprwayland-scanner",
	"cpio",
]
