[managers.system]
items = [
    # arduino
    "arduino-cli",
    "7zip",

    # java
    "jdk-openjdk",
    "gradle",

	# cpp
	"base-devel",
	"cmake",
	"meson",
	"ninja",
	"clang",
	"gcc",
	"gdb",

	# hyprland
	"pixman",

	# utils
	"cpio",
]
