[managers.system]
items = [
    # arduino
    "arduino-cli",
    "7zip",
	"uucp",

    # java
    "jdk-openjdk",
    "gradle",

	# cpp
	"base-devel",
	"cmake",
	"meson",
	"ninja",
	"clang",
	"gcc",
	"gdb",

	# hyprland
	"pixman",

	# utils
	"cpio",

	# js things
	"npm",
	"mosquitto",

	# docker things
	"docker",

	# python things
	"uv",
]
