[managers.system]
items = [
	"hyprland",
	"uwsm",
	"libnewt",
	"kitty",

	## switcher
	"tofi",

	## font
	"ttf-iosevka-nerd",
	"noto-fonts-cjk",
	"noto-fonts-emoji",
	"ttf-jigmo",

	## japanese input
	"fcitx5-im",
	"fcitx5-mozc",

	## browser
	"qutebrowser",

	## screensharing
	"xdg-desktop-portal-hyprland",
]
