[managers.system]
items = [
	# utility
	"tldr",
	"less",
	"stow",

	# file navigation
	"yazi",
	"fzf",
	"fd",

	# build system
	"base-devel",

	# watch keys code
	"wev",

	# sounds
	"sof-firmware",
	"pipewire",
	"pipewire-audio",
	"pipewire-alsa",
	"pipewire-pulse",
	"pipemixer-git",
]
