[managers.system]
items = [
	# shell
	"zsh",
	"starship",

	# my beloved
	"neovim-nightly",

	# git things
	"git",
	"openssh",

	# entertainment
	"mpv",
	"yt-dlp",
	"socat",
]

[managers.service]
items = [
	"zsh-pohl",
	"stow-service",
]
