[managers.system]
items = [
	# shell
	"zsh",
	"starship",

	# my beloved
	"neovim-nightly",
	"fastfetch",

	# git things
	"git",
	"openssh",

	# entertainment
	"mpv",
	"yt-dlp",
	"socat",

	# pdf
	"pdfjs",

	# office
	"libreoffice-fresh",
]

[managers.service]
items = [
	"zsh-pohl",
	"stow-service",
]
