[managers.system]
items = [
	# shell
	"zsh",
	"starship",

	# my beloved
	"neovim-nightly",
	"tmux",
	"fastfetch",
	"htop",
	"vial-appimage",

	# git things
	"git",
	"openssh",

	# entertainment
	"mpv",
	"yt-dlp",
	"socat",

	# pdf
	"pdfjs",

	# office
	"libreoffice-fresh",

	# screen recording, etc
	"obs-studio",
	"hyprshot",

]

[managers.service]
items = [
	"zsh-pohl",
	"stow-service",
	"tmux-plugin-manager",
]
