# --------------------- #
#    Generation File    #
# --------------------- #

# Other generation files to import. (Example: intensive_apps -> ~/.config/rebos/imports/intensive_apps.toml)
imports = [
    "system",
    "hyprland",
    "user",
    "coding",
]

[managers.system]
items = []

[managers.flatpak]
items = []

[managers.cargo]
items = []
